on: [push, pull_request]
name: Run Tests
jobs:
    build:
        runs-on: windows-latest
        steps:
        - name: Run tests
          run: cd PL1.2/bin && CMD tree && runner ../../tests/viewstmt.poopy

    
