on: [push, pull_request]
name: Run Tests
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Clone
          run: git clone https://github.com/zurgeg/poopy-lang.git
        - name: Run tests
          run: python3 PL1.2/runner.py tests/viewstmt.poopy

    
