on: [push, pull_request]
name: Run Tests
jobs:
    build:
        runs-on: windows-latest
        steps:
        - name: Run tests
          run: CMD copy PL1.2/bin/runner.exe runner.exe /B && runner tests/viewstmt.poopy

    
