on: [push, pull_request]
name: Run Tests
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Clone
          run: git clone https://github.com/zurgeg/poopy-lang.git
        - name: Install requirements
          run: pip3 install setuptools && pip3 install lark-parser
        - name: Run tests
          run: python3 poopy-lang/PL1.3/runner.py poopy-lang/tests/viewstmt.poopy

    
